lsh:
	g++ --std=c++11 -Wall -g -o lsh main_lsh.cpp hash.cpp functions.cpp functions_lsh.cpp -lm

# clean house
clean:
	rm -f main_lsh.o hash.o functions.o functions_lsh.o lsh

# do a bit of accounting
count:
	wc main_lsh.cpp functions.cpp functions_lsh.cpp hash.cpp
